### ISSUE TITLE
CaRtGS Added to awesome-Implicit-NeRF-SLAM Repo

### ISSUE THREAD

**Issue by DoongLi** [DapengFeng/cartgs#1]
Hi, this message serves as a reminder that your paper ”CaRtGS: Computational Alignment for Real-Time Gaussian Splatting SLAM“, has been included in the repository.  https://github.com/DoongLi/awesome-Implicit-NeRF-SLAM.
If there is any missing information about your work on this repository (including paper links, code, datasets, website, etc), please let us know or submit a pull request (PR) directly.

**Comment by DapengFeng** [comment]
Thank you for your collection! :)
