### ISSUE TITLE
About the installation of build.sh

### ISSUE THREAD

**Issue by DYH200009** [DapengFeng/cartgs#2]
An error occurred when I used build.sh

nvcc fatal : Unsupported gpu architecture ‘compute_'

This seems to be a GPU architecture issue, do you have any suggestions

**Comment by DYH200009** [comment]
![image](https://github.com/user-attachments/assets/53c96203-0e4b-49a1-9237-aeae793faa26)

**Comment by DapengFeng** [comment]
Could you provide more details on the compilation environments, or share the complete CMake log file?

**Comment by DYH200009** [comment]
> Could you provide more details on the compilation environments, or share the complete CMake log file?

The system configuration includes Ubuntu 22.04, an RTX 3090 server, CUDA version 11.8, the GNU C++ compiler version 11.4, and CMake version 3.22.1. A screenshot of the CMake error is provided below.

![image](https://github.com/user-attachments/assets/4703862b-c400-4f72-a672-2eee79b032c5)

**Comment by DapengFeng** [comment]
Try to identify the CUDA architectures by `-DCMAKE_CUDA_ARCHITECTURES="native"`, for example, `-DCMAKE_CUDA_ARCHITECTURES="86"` according to your [GPU Compute Capability](https://developer.nvidia.com/cuda-gpus).

**Comment by DapengFeng** [comment]
> Try to identify the CUDA architectures by `-DCMAKE_CUDA_ARCHITECTURES="native"`, for example, `-DCMAKE_CUDA_ARCHITECTURES="86"` according to your [GPU Compute Capability](https://developer.nvidia.com/cuda-gpus).

Or update the CMake version to 3.30+, which can automatically identify GPU compute capability.

**Comment by DYH200009** [comment]
* 1 Thank you for your assistance. Following the implementation of the DCAMAKE_CUDA_ARCHITECTURES=86, the issue has been successfully resolved. However, I would like to inquire whether there was a ninja error during the installation process, although it did not impede the completion of the installation.
![image](https://github.com/user-attachments/assets/a14ff203-6f03-40b9-913a-90c64e52df0d)
* 2 Besides, there is no replica_rgbd file in my bin folder. How can I get this file? Is it generated by CARTGS

**Comment by DapengFeng** [comment]
It appears that ORB_SLAM3 is not building successfully. I can't assist you without seeing a CMake compilation log message.
